# Generated by Django 5.2 on 2025-09-01 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_product_detail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product_detail',
        ),
    ]
